### ISSUE TITLE
Geef mij eten

### ISSUE THREAD

**Issue by robinnesla** [robinnesla/TestReposi#1]
Ik heb honger. ik ben niet leuk als ik honger heb!!!! >:(

**Comment by 423967mv** [comment]
vol au vent

**Comment by tcbcedric** [comment]
hmmmmmmm het water komt al in mijne mond <3

**Comment by tcbcedric** [comment]
NO WE MUST KEEP THE COMMENT TRAIN GOING!!!

**Comment by tcbcedric** [comment]
THERE ARE NO BRAKES ON THE COMMENT TRAIN!!!

**Comment by 423967mv** [comment]
Dus we hebben nodig: domeinmodel, activity diagram, SSD + OC, SD en DCD, neem ik alvast de eerste 2 voor m'n rekening? Morgen moet het af zijn hé :p
